# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-03-18 12:05:14
"""
import arcpy

def BuildAddressPoints():  # Build address points

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    Taxlots = "Taxlots"
    NearMe_gdb_2_ = "K:\\Social_Services\\NearMe\\NearMe.gdb"

    # Process: Feature To Point (Feature To Point) (management)
    address_pt_2_ = "K:\\Social_Services\\NearMe\\NearMe.gdb\\address_pt"
    arcpy.management.FeatureToPoint(in_features=Taxlots, out_feature_class=address_pt_2_, point_location="CENTROID")

    # Process: Enable Editor Tracking (Enable Editor Tracking) (management)
    Modified_Input_Dataset = arcpy.management.EnableEditorTracking(in_dataset=address_pt_2_, creator_field="created_by", creation_date_field="created_date", last_editor_field="edit_by", last_edit_date_field="edit_date", add_fields="ADD_FIELDS", record_dates_in="DATABASE_TIME")[0]

    # Process: Delete Field (Delete Field) (management)
    Update_Input_Table = arcpy.management.DeleteField(in_table=Modified_Input_Dataset, drop_field=["OBJECTID1", "County"])[0]

    # Process: Add Fields (multiple) (Add Fields (multiple)) (management)
    Updated_Input_Table = arcpy.management.AddFields(in_table=Update_Input_Table, field_description=[["source", "TEXT", "", "2", "AT", "address_source"]])[0]

    # Process: Create Domain (Create Domain) (management)
    NearMe_gdb = arcpy.management.CreateDomain(in_workspace=NearMe_gdb_2_, domain_name="address_source", domain_description="Source of situs data", field_type="TEXT", domain_type="CODED", split_policy="DEFAULT", merge_policy="DEFAULT")[0]

    # Process: Add Coded Value To Domain (Add Coded Value To Domain) (management)
    NearMe_gdb_3_ = arcpy.management.AddCodedValueToDomain(in_workspace=NearMe_gdb, domain_name="address_source", code="AT", code_description="Accessment and Taxation taxlot data")[0]

    # Process: Add Coded Value To Domain (2) (Add Coded Value To Domain) (management)
    NearMe_gdb_5_ = arcpy.management.AddCodedValueToDomain(in_workspace=NearMe_gdb, domain_name="address_source", code="GE", code_description="Geocoded (Esri)")[0]

    # Process: Add Coded Value To Domain (3) (Add Coded Value To Domain) (management)
    NearMe_gdb_6_ = arcpy.management.AddCodedValueToDomain(in_workspace=NearMe_gdb, domain_name="address_source", code="M", code_description="Manual")[0]

    # Process: Reverse Geocode (Reverse Geocode) (geocoding)
    Output_Feature_Class = "K:\\Social_Services\\NearMe\\NearMe.gdb\\address_pt_ReverseGeocode"
    arcpy.geocoding.ReverseGeocode(in_features=address_pt_2_, in_address_locator="", out_feature_class=Output_Feature_Class, address_type="ADDRESS", search_distance="100 Meters", feature_type="", location_type="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"K:\Social_Services\NearMe\NearMe.gdb", workspace=r"K:\Social_Services\NearMe\NearMe.gdb"):
        BuildAddressPoints()
