# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2021-02-09 16:20:08
"""
import arcpy

def Republish():  # Prepare data for republishing

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    # Process: Manage Map Server Cache Tiles (Manage Map Server Cache Tiles) (server)
    MapServer_2_ = "https://delta.co.clatsop.or.us/server/rest/services/Hosted/Astoria_downtown/MapServer"
    Area_Of_Interest = "in_memory\\feature_set1"

    Output_Map_Service_URL = arcpy.server.ManageMapServerCacheTiles(input_service=MapServer_2_, 
        scales=[9027.977411, 4513.988705, 2256.994353], 
        update_mode="RECREATE_ALL_TILES", 
        num_of_caching_service_instances=-1, area_of_interest=Area_Of_Interest, 
        update_extent="-13787096.1199077 5807735.98208904 -13783753.9108459 5808943.68713598", 
        wait_for_job_completion="WAIT", 
        portal_url="")[0]

    # Process: Manage Map Server Cache Tiles (2) (Manage Map Server Cache Tiles) (server)
    MapServer_3_ = "https://delta.co.clatsop.or.us/server/rest/services/Clatsop_County/MapServer"
    Area_Of_Interest_2_ = "in_memory\\feature_set2"

    Output_Map_Service_URL_2_ = arcpy.server.ManageMapServerCacheTiles(input_service=MapServer_3_, 
        scales=[1155581.108577, 577790.554289, 288895.277144, 144447.638572, 72223.819286, 36111.909643, 18055.954822, 9027.977411, 4513.988705, 2256.994353, 1128.497176], 
        update_mode="RECREATE_ALL_TILES", 
        num_of_caching_service_instances=-1, 
        area_of_interest=Area_Of_Interest_2_, 
        update_extent="-13833219.0488 5721706.2156 -13707969.6412 5842603.9323", 
        wait_for_job_completion="WAIT", 
        portal_url="")[0]

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"K:\webmaps\Basemap_PRO\Emergency.gdb", workspace=r"K:\webmaps\Basemap_PRO\Emergency.gdb"):
        Republish()

